marker([A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14], 14) :- not_equal(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14), !.
marker([A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14 | _], 14) :- not_equal(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14), !.
marker([_, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14 | L], N) :- marker([A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14 | L], NN), N is NN + 1.

%used generator.cpp to create not_equal
not_equal(A, A, _, _, _, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(A, _, A, _, _, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, A, A, _, _, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(A, _, _, A, _, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, A, _, A, _, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, A, A, _, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(A, _, _, _, A, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, A, _, _, A, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, A, _, A, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, A, A, _, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(A, _, _, _, _, A, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, A, _, _, _, A, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, A, _, _, A, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, A, _, A, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, A, A, _, _, _, _, _, _, _, _) :- !, fail.
not_equal(A, _, _, _, _, _, A, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, A, _, _, _, _, A, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, A, _, _, _, A, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, A, _, _, A, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, A, _, A, _, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, A, A, _, _, _, _, _, _, _) :- !, fail.
not_equal(A, _, _, _, _, _, _, A, _, _, _, _, _, _) :- !, fail.
not_equal(_, A, _, _, _, _, _, A, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, A, _, _, _, _, A, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, A, _, _, _, A, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, A, _, _, A, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, A, _, A, _, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, A, A, _, _, _, _, _, _) :- !, fail.
not_equal(A, _, _, _, _, _, _, _, A, _, _, _, _, _) :- !, fail.
not_equal(_, A, _, _, _, _, _, _, A, _, _, _, _, _) :- !, fail.
not_equal(_, _, A, _, _, _, _, _, A, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, A, _, _, _, _, A, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, A, _, _, _, A, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, A, _, _, A, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, A, _, A, _, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, A, A, _, _, _, _, _) :- !, fail.
not_equal(A, _, _, _, _, _, _, _, _, A, _, _, _, _) :- !, fail.
not_equal(_, A, _, _, _, _, _, _, _, A, _, _, _, _) :- !, fail.
not_equal(_, _, A, _, _, _, _, _, _, A, _, _, _, _) :- !, fail.
not_equal(_, _, _, A, _, _, _, _, _, A, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, A, _, _, _, _, A, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, A, _, _, _, A, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, A, _, _, A, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, A, _, A, _, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, A, A, _, _, _, _) :- !, fail.
not_equal(A, _, _, _, _, _, _, _, _, _, A, _, _, _) :- !, fail.
not_equal(_, A, _, _, _, _, _, _, _, _, A, _, _, _) :- !, fail.
not_equal(_, _, A, _, _, _, _, _, _, _, A, _, _, _) :- !, fail.
not_equal(_, _, _, A, _, _, _, _, _, _, A, _, _, _) :- !, fail.
not_equal(_, _, _, _, A, _, _, _, _, _, A, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, A, _, _, _, _, A, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, A, _, _, _, A, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, A, _, _, A, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, A, _, A, _, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, A, A, _, _, _) :- !, fail.
not_equal(A, _, _, _, _, _, _, _, _, _, _, A, _, _) :- !, fail.
not_equal(_, A, _, _, _, _, _, _, _, _, _, A, _, _) :- !, fail.
not_equal(_, _, A, _, _, _, _, _, _, _, _, A, _, _) :- !, fail.
not_equal(_, _, _, A, _, _, _, _, _, _, _, A, _, _) :- !, fail.
not_equal(_, _, _, _, A, _, _, _, _, _, _, A, _, _) :- !, fail.
not_equal(_, _, _, _, _, A, _, _, _, _, _, A, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, A, _, _, _, _, A, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, A, _, _, _, A, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, A, _, _, A, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, A, _, A, _, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, _, A, A, _, _) :- !, fail.
not_equal(A, _, _, _, _, _, _, _, _, _, _, _, A, _) :- !, fail.
not_equal(_, A, _, _, _, _, _, _, _, _, _, _, A, _) :- !, fail.
not_equal(_, _, A, _, _, _, _, _, _, _, _, _, A, _) :- !, fail.
not_equal(_, _, _, A, _, _, _, _, _, _, _, _, A, _) :- !, fail.
not_equal(_, _, _, _, A, _, _, _, _, _, _, _, A, _) :- !, fail.
not_equal(_, _, _, _, _, A, _, _, _, _, _, _, A, _) :- !, fail.
not_equal(_, _, _, _, _, _, A, _, _, _, _, _, A, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, A, _, _, _, _, A, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, A, _, _, _, A, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, A, _, _, A, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, _, A, _, A, _) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, _, _, A, A, _) :- !, fail.
not_equal(A, _, _, _, _, _, _, _, _, _, _, _, _, A) :- !, fail.
not_equal(_, A, _, _, _, _, _, _, _, _, _, _, _, A) :- !, fail.
not_equal(_, _, A, _, _, _, _, _, _, _, _, _, _, A) :- !, fail.
not_equal(_, _, _, A, _, _, _, _, _, _, _, _, _, A) :- !, fail.
not_equal(_, _, _, _, A, _, _, _, _, _, _, _, _, A) :- !, fail.
not_equal(_, _, _, _, _, A, _, _, _, _, _, _, _, A) :- !, fail.
not_equal(_, _, _, _, _, _, A, _, _, _, _, _, _, A) :- !, fail.
not_equal(_, _, _, _, _, _, _, A, _, _, _, _, _, A) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, A, _, _, _, _, A) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, A, _, _, _, A) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, _, A, _, _, A) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, _, _, A, _, A) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, _, _, _, A, A) :- !, fail.
not_equal(_, _, _, _, _, _, _, _, _, _, _, _, _, _).

run(N) :- string_to_list("rnttlvtttmnmpmhpmmzvmmhpmmnrntnnsnrnndvnddmbbtptssjcczmmbwmbmwwmmflfggwzzhjjgppwrwdwqwbbbmwbwgggqccmlmdmgdgqgpqgpgzzndddgdbbsvvfsfppwjwzjjcnjccwrwrprgppbpddnccjggfrggqngqgdqgddvsshqhmqqfvqvlvwvnwwmccrpcczvcczzgsgwwlggqsggmdgglblpblltbbzrbzzcscgccwssbddsmddzzvvhjjwjwrjwrwfftmttplldnllqttdhddmvdmmhsmsmqsqwqpqbpqppqdppbnpnhhppjbbrzrbrggdbddnrdrzrdrpdppzzfzrzgzllwlwzlllwtltslttlmtmqqbbzmzhmmjjwrjrrnzrzhzmmtbbrppmmfddjhdjdsdllrbbpfphpzpwwjvwwdpwpzwwzrrfnfwwfbbpttzjtjptpvvsfvvljjrzzmdmsddpvpgvvdcdwcwhwghwggrjjhdjhddzhhwbhwbwwbrwwrfrmfrfvrfftzzqrzqrqtrqtrqtrqttgctclcwlwwvqqnlnqlnnndmnmggznzhzqzggzrzbbrwbrwrvvscvvmvhmvvbsbjsjfjpfpqpbbbbjtjptpprnndpnnrsswffmnnjhhpqhqwhhbwhbhgbbfrbrjjpmjmzzdzjdjffcvvtwttrrcscvcncqcfcwwpgpfptpcpspllcfcssgbglgdllcdcmcpcqclctcvtvvbhbbdhhczhzshzhbhchzchchlcllwswqqmpmbbqwwzgzhggczgzffsgggjjlcjjpnjjfqjfjvfvrfrlrvvpfpcfcbffnmfmbmbgggplldblddvcvjcvvmbmmmrvrvvnhhqttgdgvdgdqgddcsclljplpbbsvbsbfsffshsgslsllzztggttfccctwtswwrvwvnnfbnnvjnvvlgvvfppmvpmmvpmmcttjffgsffcllncntcncfclcgcppvdvpvrvbrrnnvrvhrvrzvrvnrvrdrnrqrnngsshqhcqqbfqqzmmmzjzqztznttjffqzfqfbqqsggclgclcddtqqdppbjppqvpqvvmqmqnqcnqcqcqvqjqzqbzzbrrgfgddgtgnnpjjbzjjbbtstzszwswggfffmnnpllfvvnwnpwpqwqwlllqlmmzcmcrcmrcmrcrffnrnssjjrdjjwwqgwqgqdggwzwjzzbfbpptctchthbbbqsqggrllldwdffvwwlrwwljwjnncmmjmvjmmqnnmrrgjgvvpqqbppqlpqllqnqdndwwlppcjcdjjcnnmddffgjjrwjrwjjhvhqvhhfssrtsrsgrrwjwhhbqqpzzrdrhrqhrqrprqqmllsszhzllcdllpmpbbmsmjjmwmssvlslwwmtwmmgvgcvggzcgzgddsjsjfsssftfcchhfmfcmcpcpvcppqggjddljjbttwrrhghqggpghgngzngznnzqnnssqlqmqbmmmqdqqhttnqqjhhphrhccbggmjjpwpbwpprdrvvjzvvtctzzmpphwpwdpdvvhbvvdvsdsjdjbdjdljjstswttnhhbfffmnngddlglqggvzvlzvzqqvbqbvbjbnjjsvjjwpjjzshrdtrjttvqnbltrfpvnztrwzrtgjpzgqdjfglqgjrgdzbhqpghdbfhlfjhbfjfjppfgljmgwljlsbmltgztthnzvdrgqlgddvqhzctdgcphfqvnpjjgzwqfvnhvzdrwtpgfdjpqnfshslqmplcprdntnhqqbqptwzvdddhcjcqrfhjqnjvpnhttblwgjwlfwntdchgfjmdbgtqtdgnzbqwzzcltwtmtqtdbvjtfvlzpcvgmrfqwfhwqmhvwhftzgmhshffnjwqbvztszsrrglqvhfpqmbnqjsfnwdwgdtmztbvqrmztfctmvptbwnfzfgdztjgnqsrsqqqnrpgzsqszzwwwgqnnnrdzhzdbqjgbvncprzcjqchzfgnclbrmphbsdwwpvwjwlbshhgjfbhjjtdqrmrcjfnrrhqrpsbglthzpvfglqspttdpwlljhnlrjpzchbrqcgtmcscjnwvpztfjdcwbnbgmbpgdthgnhbrtwftnscbsrndghbslflpcpjwbcjnhzcwdcslmzqbtrlnzmntlpjcsctnsqwtbffqlhfgcsflvfwnmczvsbflnnnzpfjfrcwhhcbtbjcbghtcwcgdbrwrgfgvpwtcwlwcmnmrtcrjbwtwlrfstztsghfvrfjzzpswpqfqpvqstvbhqfjlgmtdlhqrhwzqpnqpllnlgzwptbgftmblqcwfcllbwfzdhrndfrvdvwzqvhnghlzvhldnnvrgqvlpfdnpmcgddjmstzsqfvzwftflrwtzqwjbbqhjpfbdztdfsgsztvvrvslgspgpdcmwszdfsddqhpzpsjgqmgzqvhchlgrmcmzwzbtwfphvgcdmhfdczhffgmqpncdjszzgwfvwsqddvbcgngbjwhmphjsmjthvbthhfwdtqmjctcmdpqpsdrnrzdgzgzctbhwsgvtjgwjbsnnjmpmqgwrnqfqbpnrpddjsrsvmcshhthwfrwmqsrjhlsrgfzvwmdzhwrvchppqldghgzflrnwqnvntmtdwmrpgbdbzvcmnqstzntvllcgzsnvrhqzsfncznhgrggmvrmgsqmhbdsjbsqqhzppfcwdrgdvfjdscrvpwtsdmcnczwbbjhvddprwtzfwslcfdcrqfszcgmhtdfvlqzqtvwngzvmmqcrqpzwzhggjnphsrmnctnfhtppglspnvzrsqfgzdfrrwbzbqwvbvbnzgmdrqrnsvdpvlgcmnggsbmbtfwrvdjrtgtgcqscnfpgswgsngdqnnscffdcnlrcpdpcbpzvqcrtjhlwvgnfhhqmprthrtcvcjjwgprqqdwfbgmzlwttjpvcjzfwbdhvngsjpgtqsvbldbcvhjhzbjzblqtqhlnbzzqfcpnzdhbplztcgvzhbgshqbccgwzhftqvtwzbwmnfrsgphhhgtsmwlqhlcchtbtggqwmbdthhmqqjtfdvfpddfdrtfjbpmwtcbfnrhwcnpdqrdtsfdmjfzdwwgnftnwpssgqtlpdbwhnzcnfmppclsswbhcdghpnslwjznqszgdtrnpncsqsnbrplrfwpbnfnvttlzcjtvhzcpzmhfsfzfjlzqqnprpdvwbfthmrswqrcqqwrnwzmgjqqsnqdblssmhngjjvprmqbswtgzzvprwhrgjqshvmwzgrgfmzlgrtzbmdlzncwqdftfsndvdfmmplswdbjtbcbvcvtpjvrqpghczpqvvpqwfbfhllbpvrrfsmsjhqbldcrwvzvcvzfffqvplbfbdbwctbjsljlfwtbcnpsbtpmcqgdvltmztvrcfsprbnvwplwhncgsdnrdmqnmcvpvvrlmlwtgvrnwvzsfctdlcfvtgqmpnbwcbwvfpmqnbjvwffpjtvvgflhrnlngrzhhttdtdbvscftsqtvbrgzfgsjvwhzjcbsqcttlgwmhhvjhwhgmmdtflfdbvnhgcblqmwjfsqnngjqfbvdnsfbgwjfhpgdgvhpbvlrtpcpvhrbtqpbffzcqrvbqwvqmmrcwtnvcgwvsqzvrwdbcnjshbnbftmmvrmjvgfdwbsjvqfdwnnvqqhbmshcrclrwhfhbtnwqvmrrvdwgcwcsrhdbqndsthmrmbjhttjtzmlflbrmhlcgsbdjcjcvwcjffnqrntpflrgfcngpchtrzpnflwjvcgbwtsnjfqsggwmwhdvbzdpjmtwlmrslnjsndjtgjmmwmdgtnfrztppzqvqhbfzqpsdhvsshddlzwcmsndrpqhndsrjnngnmgmzrvchwlqgdnbssbhpbpgwpsrcnbphpslvqplhpgdhmrnwwjmhvnsfjmrfwtvjjrmgptvjffhbgpmfgmgrcjrwqhccssrqjpljbpwcvsfdtmbhzsmsjsgblgpcqszsttfclrjcnsslmngmbmwqfhddbvmbvwmrmvglsl", L), marker(L, N).
